# Generated by Django 3.2 on 2023-05-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_title_relise_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='relise_year',
            field=models.IntegerField(default=1, verbose_name='Дата релиза.'),
            preserve_default=False,
        ),
    ]
