# Generated by Django 3.2 on 2023-05-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
