# Generated by Django 3.2 on 2023-05-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_title_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reviw',
            new_name='review',
        ),
    ]
