# Generated by Django 3.2 on 2023-05-30 09:32

import django.core.validators
from django.db import migrations, models
import reviews.validator


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230530_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(10, 'Средняя оценка не можожет быть больше 10.')], verbose_name='Рейтинг произведения.'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[reviews.validator.yaer_validator], verbose_name='Дата релиза.'),
        ),
    ]
