# Generated by Django 3.2 on 2023-05-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230530_1232'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='title-author',
        ),
    ]
